### ISSUE TITLE
Sourcecode needs a license

### ISSUE THREAD

**Issue by somas95** [m3rt32/NodeBasedDialogueSystem#2]
Well, technically it doesn't, but it would be nice to have it if you want other devs to be able to reuse and share your code. I suggest https://choosealicense.com/ to choose one that fits your needs. In any case, thanks for the tutorials and the provided code

**Comment by m3rt32** [comment]
Thanks for the suggestion! I'll update the license info soon :)

**Comment by m3rt32** [comment]
Done with commit 3df6a028b5a8c08a986b0f7e4e5f0a6a15ee3fdb
